# Generated by Django 2.2.4 on 2019-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('picture_url', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('registered_time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_id', models.CharField(max_length=11)),
                ('message', models.CharField(max_length=1000)),
                ('sender_id', models.CharField(max_length=11)),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_photo', models.CharField(max_length=1000)),
                ('sender_phone', models.CharField(max_length=50)),
                ('date_time', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('picture_url', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('pickup_time', models.CharField(max_length=200)),
                ('lifespan', models.CharField(max_length=20)),
                ('likes', models.CharField(max_length=20)),
                ('requests', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('registered_time', models.CharField(max_length=50)),
                ('is_like', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=11)),
                ('member_id', models.CharField(max_length=11)),
                ('liked_time', models.CharField(max_length=50)),
            ],
        ),
    ]
